#!/bin/bash

TheSkyX_Install=~/Library/Application\ Support/Software\ Bisque/TheSkyX\ Professional\ Edition/TheSkyXInstallPath.txt
echo "TheSkyX_Install = $TheSkyX_Install"

if [ ! -f "$TheSkyX_Install" ]; then
    echo TheSkyXInstallPath.txt not found
    exit 1
fi


TheSkyX_Path=$(<"$TheSkyX_Install")
echo "Installing to $TheSkyX_Path"

if [ ! -d "$TheSkyX_Path" ]; then
    echo "Coudln't find TheSkyX application location"
    exit 1
fi

if [ -d "$TheSkyX_Path/PlugIns" ]; then
	PLUGINS_DIR="$TheSkyX_Path/PlugIns"
elif [ -d "$TheSkyX_Path/Resources/Common/PlugIns64" ]; then
	PLUGINS_DIR="$TheSkyX_Path/Resources/Common/PlugIns64"
else
	PLUGINS_DIR="$TheSkyX_Path/Resources/Common/PlugIns"

echo "Installing in $PLUGINS_DIR/DomePlugIns/"

cp "/tmp/RigelDome_X2/domelist RigelDome.txt" "$TheSkyX_Path/Resources/Common/Miscellaneous Files/"
if [ "$?" -ne "0" ]; then exit 1; fi
cp "/tmp/RigelDome_X2/RigelDome.ui" "$PLUGINS_DIR/DomePlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi
cp "/tmp/RigelDome_X2/Pulsar.png" "$PLUGINS_DIR/DomePlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi
cp "/tmp/RigelDome_X2/libRigelDome.dylib" "$PLUGINS_DIR/DomePlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

app_owner=`/usr/bin/stat -n -f "%u" "$TheSkyX_Path" | xargs id -n -u`
if [ ! -z "$app_owner" ]; then
	chown $app_owner "$TheSkyX_Path/Resources/Common/Miscellaneous Files/domelist RigelDome.txt"
	chown $app_owner "$PLUGINS_DIR/DomePlugIns/RigelDome.ui"
	chown $app_owner "$PLUGINS_DIR/DomePlugIns/Pulsar.png"
	chown $app_owner "$PLUGINS_DIR/DomePlugIns/libRigelDome.dylib"
fi
chmod 644 "$TheSkyX_Path/Resources/Common/Miscellaneous Files/domelist RigelDome.txt"
chmod 755 "$PLUGINS_DIR/DomePlugIns/libRigelDome.dylib"
chmod 644 "$PLUGINS_DIR/DomePlugIns/RigelDome.ui"
chmod 644 "$PLUGINS_DIR/DomePlugIns/Pulsar.png"
rm -rf /tmp/RigelDome_X2

